PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
EXCLUDED_DIRECTORIES: [".git"]
IGNORE_GITIGNORED_FILES: true
ENABLE:
  - EDITORCONFIG
  - CREDENTIALS
  - JSON
  - MARKDOWN
  - YAML
  - POWERSHELL
DISABLE_LINTERS:
  - JSON_JSONLINT
  - JSON_V8R
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - YAML_V8R
EDITORCONFIG_FILTER_REGEX_EXCLUDE: "(Modules|root/)"
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: "(Modules|root/|settings.json)"
JSON_ESLINT_PLUGIN_JSONC_FILTER_REGEX_EXCLUDE: "(Modules|root/|settings.json)"
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".markdown-lint.yml"
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(Modules)"
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(\\.azuredevops)"
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "(\\.azuredevops)"
POWERSHELL_FILTER_REGEX_EXCLUDE: "(Modules)"
CONFIG_REPORTER: false
UPDATED_SOURCES_REPORTER: true
CONSOLE_REPORTER: true
LOG_FILE: mega-linter-beta.log
LOG_LEVEL: INFO
PRINT_ALL_FILES: false
APPLY_FIXES: all
FAIL_IF_UPDATED_SOURCES: true
