PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
EXCLUDED_DIRECTORIES: [".git"]
IGNORE_GITIGNORED_FILES: true
ENABLE:
  - EDITORCONFIG
  - JSON
  - MARKDOWN
  - YAML
  - POWERSHELL
  - REPOSITORY
  - SPELL
DISABLE_LINTERS:
  - JSON_JSONLINT
  - JSON_V8R
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - YAML_V8R
EDITORCONFIG_FILTER_REGEX_EXCLUDE: "(Modules|root/)"
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: "(Modules|root/|settings.json)"
JSON_ESLINT_PLUGIN_JSONC_FILTER_REGEX_EXCLUDE: "(Modules|root/|settings.json)"
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".markdown-lint.yml"
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(Modules)"
POWERSHELL_FILTER_REGEX_EXCLUDE: "(Modules)"
POWERSHELL_POWERSHELL_CONFIG_FILE: ".powershell-psscriptanalyzer.psd1"
REPOSITORY_GITLEAKS_CONFIG_FILE: ".gitleaks.toml"
REPOSITORY_GITLEAKS_DISABLE_ERRORS: true
SPELL_CSPELL_DISABLE_ERRORS: true
SPELL_PROSELINT_DISABLE_ERRORS: true
CONFIG_REPORTER: false
UPDATED_SOURCES_REPORTER: true
CONSOLE_REPORTER: true
LOG_FILE: mega-linter-v6.log
LOG_LEVEL: INFO
PRINT_ALL_FILES: false
APPLY_FIXES: all
DEFAULT_BRANCH: main
VALIDATE_ALL_CODEBASE: false
